"""
Django settings for synelweb project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import os, dj_database_url
from urllib.parse import urlparse

load_dotenv(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env"))

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Security / Debug ---
SECRET_KEY = os.environ.get("SECRET_KEY", "insecure-default-key")
DEBUG = os.environ.get("DEBUG", "False") == "True"

# Load ALLOWED_HOSTS from environment to avoid committing hosts to source
ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv(
        "ALLOWED_HOSTS",
        "synelweb.fly.dev,synelweb.hu,synelweb.vercel.app,synelweb-r394y2f2i-szilveszters-projects-d6dfe6cc.vercel.app,localhost,127.0.0.1",
    ).split(",")
    if h.strip()
]

# --- Apps ---
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "cloudinary_storage",  # cloudinary storage
    "cloudinary",  # cloudinary
    # project apps
    "core",
    "packages",
    "review",
    "projects",
    "blog",
    "nested_admin",  # nested admin
]

# Cloudinary storage settings - require CLOUDINARY_URL
CLOUDINARY_URL = os.getenv("CLOUDINARY_URL")
if not CLOUDINARY_URL:
    raise RuntimeError("CLOUDINARY_URL is required for media storage. Set CLOUDINARY_URL in the environment.")

# Use cloudinary storage for all media files
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
MEDIA_URL = "/media/"

# Parse CLOUDINARY_URL (format: cloudinary://API_KEY:API_SECRET@CLOUD_NAME)
parsed_cloud = urlparse(CLOUDINARY_URL)
netloc = parsed_cloud.netloc or ""
api_key = None
api_secret = None
cloud_name = None
try:
    creds, cloud_name = netloc.split("@")
    api_key, api_secret = creds.split(":")
except Exception:
    # fallback to individual env vars if parsing fails
    api_key = os.getenv("CLOUDINARY_API_KEY")
    api_secret = os.getenv("CLOUDINARY_API_SECRET")
    cloud_name = os.getenv("CLOUDINARY_CLOUD_NAME")

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": cloud_name,
    "API_KEY": api_key,
    "API_SECRET": api_secret,
}

# --- Middleware ---
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "synelweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "synelweb.wsgi.application"

# --- Database: Neon + PgBouncer (transaction pooling) ---
# Fontos: sslmode=require + CONN_MAX_AGE=0 + server-side cursors tiltása

db_url = os.getenv("DATABASE_URL")
pg_host = os.getenv("POSTGRES_HOST")

if db_url:
    DATABASES = {
        "default": dj_database_url.parse(
            db_url,
            conn_max_age=0,
            ssl_require=True,
        )
    }
    DISABLE_SERVER_SIDE_CURSORS = True
elif pg_host:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": pg_host,
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "OPTIONS": {"sslmode": "require"},
            "CONN_MAX_AGE": 0,
        }
    }
    DISABLE_SERVER_SIDE_CURSORS = True
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "build.db",
        }
    }

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- I18N ---
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --- Static / Media ---
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Use CompressedStaticFilesStorage instead of Manifest version to avoid strict mode errors
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# --- CORS / CSRF ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://synelweb.vercel.app",
    "https://synelweb-r394y2f2i-szilveszters-projects-d6dfe6cc.vercel.app",
    "https://synelweb.hu",
    "https://www.synelweb.hu",
]
CSRF_TRUSTED_ORIGINS = [
    "https://synelweb.fly.dev",
    "https://api.synelweb.hu",
    "https://synelweb.vercel.app",
    "https://synelweb-r394y2f2i-szilveszters-projects-d6dfe6cc.vercel.app",
    "https://synelweb.hu",
    "https://www.synelweb.hu",
]

# --- Default PK type ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- (Opcionális, de hasznos) Prod security ---
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# --- (Opcionális) Logging: könnyebb hibakeresés fly logs-ban ---
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.db.backends": {"handlers": ["console"], "level": "WARNING"},
        "django.security": {"handlers": ["console"], "level": "WARNING"},
    },
}
