# Generated by Django 5.2.1 on 2025-08-12 08:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "preview_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Kép URL-je (pl. https://példa.hu/kep.png)",
                        max_length=500,
                    ),
                ),
                ("description", models.TextField()),
                ("is_discounted", models.BooleanField(db_index=True, default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Vesszővel elválasztva: pl. seo, statikus oldal, pwa",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "project_type",
                    models.CharField(
                        db_index=True,
                        help_text="Pl.: Landing Page, Social Media, Webshop",
                        max_length=100,
                    ),
                ),
                (
                    "preview_video_url",
                    models.URLField(
                        blank=True,
                        help_text="Projekt bemutató videó URL-je (pl. YouTube link)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "preview_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Előnézeti kép URL-je",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Jóváhagyás után jelenjen meg"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(help_text="Kép URL-je", max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "order"), name="uniq_project_order"
                    )
                ],
            },
        ),
    ]
