# Generated by Django 5.2.1 on 2025-08-19 13:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="preview_image_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="preview_video_url",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, help_text="Projekt részletes leírása"),
        ),
        migrations.AddField(
            model_name="project",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Előnézeti kép",
                null=True,
                upload_to=core.models.project_media_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="preview_video",
            field=models.FileField(
                blank=True,
                help_text="Projekt bemutató videó (pl. mp4)",
                null=True,
                upload_to=core.models.project_media_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.project_media_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
