# Generated by Django 5.2.1 on 2025-08-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_project_preview_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Akciós ár (pl. 39999.00)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Normál ár (pl. 49999.00)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
